/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author ilham
 */
import java.sql.Connection;
import koneksi.koneksi;
import frontend.dataBarang;
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private Connection conn = new koneksi().connect();
    public Menu() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnLbr = new javax.swing.JButton();
        btnLbk = new javax.swing.JButton();
        btnLbm = new javax.swing.JButton();
        btnBm = new javax.swing.JButton();
        btnBk = new javax.swing.JButton();
        btnBr = new javax.swing.JButton();
        btnDb = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(245, 240, 225));

        btnLbr.setBackground(new java.awt.Color(255, 110, 64));
        btnLbr.setForeground(new java.awt.Color(30, 61, 89));
        btnLbr.setText("Laporan Barang Rusak");
        btnLbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLbrActionPerformed(evt);
            }
        });

        btnLbk.setBackground(new java.awt.Color(255, 110, 64));
        btnLbk.setForeground(new java.awt.Color(30, 61, 89));
        btnLbk.setText("Laporan Barang Keluar");
        btnLbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLbkActionPerformed(evt);
            }
        });

        btnLbm.setBackground(new java.awt.Color(255, 110, 64));
        btnLbm.setForeground(new java.awt.Color(30, 61, 89));
        btnLbm.setText("Laporan Barang Masuk");
        btnLbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLbmActionPerformed(evt);
            }
        });

        btnBm.setBackground(new java.awt.Color(255, 110, 64));
        btnBm.setForeground(new java.awt.Color(30, 61, 89));
        btnBm.setText("Barang Masuk");
        btnBm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBmActionPerformed(evt);
            }
        });

        btnBk.setBackground(new java.awt.Color(255, 110, 64));
        btnBk.setForeground(new java.awt.Color(30, 61, 89));
        btnBk.setText("Barang Keluar");
        btnBk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBkActionPerformed(evt);
            }
        });

        btnBr.setBackground(new java.awt.Color(255, 110, 64));
        btnBr.setForeground(new java.awt.Color(30, 61, 89));
        btnBr.setText("Barang Rusak");
        btnBr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrActionPerformed(evt);
            }
        });

        btnDb.setBackground(new java.awt.Color(255, 110, 64));
        btnDb.setForeground(new java.awt.Color(30, 61, 89));
        btnDb.setText("Data Barang");
        btnDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDbActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 110, 64));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 61, 89));
        jLabel1.setText("ATK INVENTORY ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnLbr))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnDb)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnBm)
                            .addGap(26, 26, 26)
                            .addComponent(btnBk)
                            .addGap(27, 27, 27)
                            .addComponent(btnBr))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(btnLbm)
                            .addGap(36, 36, 36)
                            .addComponent(btnLbk))))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnDb)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBk)
                    .addComponent(btnBr)
                    .addComponent(btnBm))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLbm)
                    .addComponent(btnLbk))
                .addGap(27, 27, 27)
                .addComponent(btnLbr)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDbActionPerformed
        // TODO add your handling code here:
        new dataBarang().setVisible(true);
    }//GEN-LAST:event_btnDbActionPerformed

    private void btnBkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBkActionPerformed
        // TODO add your handling code here:
        new barangKeluar().setVisible(true);
    }//GEN-LAST:event_btnBkActionPerformed

    private void btnBrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrActionPerformed
        // TODO add your handling code here:
        new barangRusak().setVisible(true);
    }//GEN-LAST:event_btnBrActionPerformed

    private void btnBmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBmActionPerformed
        // TODO add your handling code here:
        new barangMasuk().setVisible(true);
    }//GEN-LAST:event_btnBmActionPerformed

    private void btnLbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLbmActionPerformed
        // TODO add your handling code here:
        new laporanbarangmasuk().setVisible(true);
    }//GEN-LAST:event_btnLbmActionPerformed

    private void btnLbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLbkActionPerformed
        // TODO add your handling code here:
        new laporanbarangkeluar().setVisible(true);
    }//GEN-LAST:event_btnLbkActionPerformed

    private void btnLbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLbrActionPerformed
        // TODO add your handling code here:
        new laporanbarangrusak().setVisible(true);
    }//GEN-LAST:event_btnLbrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBk;
    private javax.swing.JButton btnBm;
    private javax.swing.JButton btnBr;
    private javax.swing.JButton btnDb;
    private javax.swing.JButton btnLbk;
    private javax.swing.JButton btnLbm;
    private javax.swing.JButton btnLbr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
